move_to_test:
  fjt_action_name: "/comau_scaled_fjt_controller/follow_joint_trajectory"
  group_name: "comau"
  tool_frame: "flange"
  ik_service_name: "/comau_ik_solver/get_ik"
  simulation: false
  z_shift: 0.3