move_to_test:
  fjt_action_name: "/comau_scaled_fjt_controller/follow_joint_trajectory"
  group_name: "comau"
  tool_frame: "flange"
  scaling: 100 #value between 0 and 100
  speed_scaling_topic: "/speed_ovr"
  ik_service_name: "/comau_ik_solver/get_ik"
  simulation: false
  pipeline_id: "ompl"
  planner_id: "BiTRRT"
  velocity_scaling_factor: 1
  acceleration_scaling_factor: 1
  joints_weights: [1,1,1,1,1,1]
  z_shift: 0.3
